apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-04-07T06:28:38Z"
  labels:
    app: deployment
  name: service
  namespace: default
  resourceVersion: "8453"
  uid: ee6f5ef5-9b1c-4597-b90b-4db93b0e1e0f
spec:
  clusterIP: 10.108.70.210
  clusterIPs:
  - 10.108.70.210
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31759
    port: 3000
    protocol: TCP
    targetPort: 8080
  selector:
    app: deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
